config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  resources :boards

  resources :status_lists

  resources :cards
  get 'new_team_card', to: 'cards#new_team_card', as: :new_team_card

  resources :teams

  resources :users

  resources :tu_linkers

  resources :all_boards

  # get 'all_boards', to: 'all_boards#index', as: :all_boards
  # get 'login', to: 'sessions#new'  
  # post 'login', to: 'sessions#create' 
  # get 'signup', to: 'users#new', as: :signup  
  # post 'signup', to: 'users#create' 
  # get "up" => "rails/health#show", as: :rails_health_check 
  # get 'boards', to: 'boards#show', as: :user_
  # get 'boards/index', to: 'boards#index', as: :tables
  # get '/boards/:id', to: 'boards#show', as: :board
  # delete 'logout', to: 'sessions#destroy', as: :logout
  # resources :users, only: [:new, :create]
 
end

app/models/tu_linker.rb
class TuLinker < ApplicationRecord

  belongs_to :team, class_name: "Team"
  belongs_to :user, class_name: "User"

end

app/controllers/tu_linkers_controller.rb
class TuLinkersController < ApplicationController
    before_action :set_user_team, only: [:show, :edit, :update, :destroy]
    before_action :set_team, only: [:index]

    def index
        @team_user_ids = @team.tu_linker_ids
    end

    def show
    end

    def new
        @tu_linker = TuLinker.new
        @team_id = params[:team_id]
    end

    def create
        @tu_linker = TuLinker.new(tu_linker_params)
        respond_to do |format|
            if @tu_linker.save
                format.html {redirect_to team_path(@tu_linker.team_id), notice: 'Usuario agregado exitosamente al equipo.'}
                format.json {render :show, status: :created, location: @tu_linker}
            else
                format.html {render :new, status: :unprocessable_entity, locals: {team_id: params[:team_id]}}
                format.json {render json: @tu_linker.errors, status: :unprocessable_entity}
            end
        end
    end

    def edit
    end

    def update
    end

    def destroy
        @tu_linker.destroy
        respond_to do |format|
            format.html {redirect_to team_path(@tu_linker.team_id), notice: 'Usuario eliminado exitosamente del equipo.'}
            format.json {head :no_content}
        end
    end

    private

    def tu_linker_params
        params.require(:tu_linker).permit(:team_id, :user_id)
    end

    def set_user_team
        @tu_linker = TuLinker.find(params[:id])
    end

    def set_team
        @team = Team.find(params[:team_id])
    end

end

app/views/tu_linkers/_form.html.erb
<% team = Team.find(@team_id) %>
<% existing_user_ids = team.users.pluck(:id) %>
<%= form_with model: @tu_linker, local: true do |form| %>
    <h1>Agregar participante a <%= team.name %></h1>
    <br>
    <div class="mb-3">
        <%= form.label :user_id, "Usuario" %>
        <%= form.collection_select :user_id, User.where.not(id: existing_user_ids), :id, :username, { prompt: "Selecciona un usuario" }, class: 'form-control rounded-pill', id: 'user_id', required: true, oninvalid: "this.setCustomValidity('Por favor, selecciona un usuario')" %>
    </div>
    <%= form.hidden_field :team_id, value: @team_id %>
    <br>
    <div class="d-flex justify-content-between">
        <%= form.submit "Agregar", class: 'btn btn-primary' %>
        <%= link_to 'Volver', tu_linkers_path(team_id: @team_id), class: 'btn btn-secondary' %>
    </div>
<% end %>

app/views/tu_linkers/_team_users.html.erb
<div class="d-flex justify-content mb-3">
    <%= link_to 'Nuevo participante', new_tu_linker_path(team_id: @team.id), class: 'btn btn-primary' %>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th scope="col">Nombre de Usuario</th>
                <th scope="col">Correo Electrónico</th>
            </tr>
        </thead>
        <tbody>
            <% if @team.users.any? %>
                <% @team.users.each do |team_user| %>
                    <tr>
                        <td><%= link_to team_user.username, user_path(team_user), class: 'text-decoration-none' %></td>
                        <td><%= team_user.email %></td>
                    </tr>
                <% end %>
            <% else %>
                <p>No hay usuarios para mostrar en este equipo.</p>
            <% end %>
        </tbody>
    </table>
</div>            

app/views/tu_linkers/index.html.erb
<div class="container">  
    <div class="card col-md-10"> 
        <h1 class="my-4">Participantes de <%= @team.name %></h1>
        <%= render 'team_users', team: @team %>
    </div>
</div>

app/views/tu_linkers/new.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-8">
            <div class="card-body">
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>