config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  resources :boards

  resources :status_lists

  resources :cards
  get 'new_team_card', to: 'cards#new_team_card', as: :new_team_card

  resources :teams

  resources :users

  resources :tu_linkers

  resources :all_boards

  # get 'all_boards', to: 'all_boards#index', as: :all_boards
  # get 'login', to: 'sessions#new'  
  # post 'login', to: 'sessions#create' 
  # get 'signup', to: 'users#new', as: :signup  
  # post 'signup', to: 'users#create' 
  # get "up" => "rails/health#show", as: :rails_health_check 
  # get 'boards', to: 'boards#show', as: :user_
  # get 'boards/index', to: 'boards#index', as: :tables
  # get '/boards/:id', to: 'boards#show', as: :board
  # delete 'logout', to: 'sessions#destroy', as: :logout
  # resources :users, only: [:new, :create]
 
end

app/models/board.rb
class Board < ApplicationRecord

    has_many :status_lists, dependent: :destroy
    belongs_to :creator, class_name: "User"
    belongs_to :team, class_name: "Team"

    after_create :create_default_status_lists

    validates :title, presence: true

    private

    def create_default_status_lists
        status_lists.create(title: 'To do')
        status_lists.create(title: 'WIP')
        status_lists.create(title: 'Done')
    end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end
    
  def show
    @status_lists = @board.status_lists.includes(:cards)
  end

  def new
    @board = Board.new
    @team_id = params[:team_id]
  end

  def create
    @board = Board.new(board_params)
    respond_to do |format|
      if @board.save
        format.html {redirect_to board_path(@board), notice: 'Tabla creada exitosamente.'}
        format.json {render :show, status: :created, location: @board}
      else
        format.html {render :new, status: :unprocessable_entity, locals: {team_id: params[:team_id]}}
        format.json {render json: @board.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html {redirect_to board_path(@board), notice: 'Tabla actualizada exitosamente.'}
        format.json {render :show, status: :created, location: @board}
      else
        format.html {render :edit, status: :unprocessable_entity, locals: {team_id: params[:team_id]}}
        format.json {render json: @board.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @board.destroy
    respond_to do |format|
      format.html {redirect_to boards_path, notice: 'Tabla eliminada exitosamente.'}
      format.json {head :no_content}
    end
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :creator_id, :team_id)
  end  

end

app/views/boards/_boards.html.erb
<% Team.all.each do |team| %>
  <div class="card mt-4 d-flex justify-content mb-3">
    <div class="card-header">
      <h2><%= team.name %></h2>
      <% if team.users.include?(current_user) =%>
        <div class="d-flex">
          <%= link_to 'Participantes', tu_linkers_path(team_id: team.id), class: 'btn btn-sm btn-info me-2' %>
          <%= link_to 'Cambiar nombre', edit_team_path(team), class: 'btn btn-sm btn-warning me-2' %>
          <% if team.creator_id == current_user.id %>
            <%= button_to 'Eliminar', team_path(team), method: :delete,  data: { turbo_confirm: '¿Estás segura/o de eliminar este proyecto?' }, class: 'btn btn-sm btn-danger' %>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if team.users.include?(current_user) =%>
      <div class="card-body">
        <% if team.boards.any? %>
          <ul class="list-group">
            <% team.boards.each do |board| %>
              <li class="list-group-item">
                <%= link_to board.title, board_path(board), class: 'plain-text:-link text-decoration-none' %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No hay tareas para mostrar en este equipo.</p>
        <% end %>
        <br>
        <div>
          <%= link_to 'Nueva tabla', new_board_path(team_id: team.id), class: 'btn btn-sm btn-primary' %>
        </div>
      </div>
    <% else %>
      <div class="card-body">
        <p>No tienes acceso a este equipo.</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/boards/_form.html.erb
<%= form_with model: board, local: true do |form| %>
    <% if @board.errors.any? %>
        <div style="color: red;">
            <h4><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h4>
            <ul>
                <% @board.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <% users = (Team.find(team_id)).users %>
    <br><br>
    <div class="form-group mb-3 col-md-12">
        <%= form.label :title, "Título" %>
        <%= form.text_field :title, class: 'form-control rounded-pill' %>
    </div>

    <%= form.hidden_field :creator_id, value: current_user.id %>
    <%= form.hidden_field :team_id, value: @team_id %>
    <br>
    <div class="d-flex justify-content-between">
        <%= form.submit 'Crear', class: 'btn btn-primary' %>
        <%= link_to 'Volver', boards_path, class: 'btn btn-secondary' %>
    </div>
<% end %>

app/views/boards/_uform.html.erb
<%= form_with model: board, local: true do |form| %>
    <% if @board.errors.any? %>
        <div style="color: red;">
            <h4><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h4>
            <ul>
                <% @board.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <br><br>
    <div class="form-group mb-3 col-md-12">
        <%= form.label :title, "Título" %>
        <%= form.text_field :title, class: 'form-control rounded-pill' %>
    </div>

    <br>
    <div class="d-flex justify-content-between">
        <%= form.submit "Actualizar", class: "btn btn-primary" %>
        <%= link_to "Volver", board_path(@board), class: "btn btn-secondary" %>
    </div>
<% end %>

app/views/boards/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-6">
            <div class="card-body">
                <h1>Cambiar nombre</h1>
                <%= render 'uform', board: @board, team_id: @team_id %>
            </div>
        </div>
    </div>
</div>

app/views/boards/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="card col-md-12">
      <div class="card-body">
        <h1 class="my-4">Equipos <%= link_to 'Nuevo', new_team_path, class: 'btn btn-primary ml btn-sm' %></h1>
        <%= render partial: 'boards' %>
      </div>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-6">
            <div class="card-body">
                <h1>Nueva tabla</h1>
                <%= render 'form', board: @board, team_id: @team_id %>
            </div>
        </div>
    </div>
</div>

app/views/boards/show.html.erb
<div class="card">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card-header">
        <br><h1><%= @board.title %></h1>
        <div class="d-flex">
          <%= link_to 'Cambiar nombre', edit_board_path(@board), class: 'btn btn-sm btn-warning me-2' %>
          <%= link_to 'Nuevo estado', new_status_list_path(board_id: @board.id), class: 'btn btn-sm btn-primary me-2' %>
          <%= button_to 'Eliminar', board_path(@board), method: :delete, data: { turbo_confirm: '¿Estás segura/o de eliminar esta tabla?' }, class: 'btn btn-sm btn-danger' %>
        </div>
      </div>
      <div class="card-body">
        <br>
        <div class="row">
          <% @status_lists.each do |status_list| %>
            <div class="col-md-4">
              <div class="card mt-4">
                <div class="card-header">
                  <h2><%= status_list.title %> <%= link_to 'Ver', status_list_path(status_list), class: 'btn btn-sm btn-info' %></h2>
                </div>
                <div class="card-body">
                  <% if status_list.cards.any? %>
                    <ul class="list-group">
                      <% status_list.cards.each do |card| %>
                        <li class="list-group-item">
                          <div>
                            <h4><strong><%= link_to card.title, card_path(card), class: 'text-decoration-none' %></strong></h4>
                          </div>
                          <div>
                            <strong>Description:</strong> <%= card.description %>
                          </div>
                          <div>
                            <strong>Priority:</strong> <%= card.priority %>
                          </div>
                          <div>
                            <strong>Creator:</strong> <%= card.creator.username %>
                          </div>
                          <div>
                            <strong>Assignee:</strong> <%= card.assignee.username if card.assignee %>
                          </div>
                        </li>
                      <% end %>
                    </ul>
                  <% else %>
                    <p class="mt-3">No hay tareas en esta lista.</p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>