config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  resources :boards

  resources :status_lists

  resources :cards
  get 'new_team_card', to: 'cards#new_team_card', as: :new_team_card

  resources :teams

  resources :users

  resources :tu_linkers

  resources :all_boards

  # get 'all_boards', to: 'all_boards#index', as: :all_boards
  # get 'login', to: 'sessions#new'  
  # post 'login', to: 'sessions#create' 
  # get 'signup', to: 'users#new', as: :signup  
  # post 'signup', to: 'users#create' 
  # get "up" => "rails/health#show", as: :rails_health_check 
  # get 'boards', to: 'boards#show', as: :user_
  # get 'boards/index', to: 'boards#index', as: :tables
  # get '/boards/:id', to: 'boards#show', as: :board
  # delete 'logout', to: 'sessions#destroy', as: :logout
  # resources :users, only: [:new, :create]
 
end

app/models/card.rb
class Card < ApplicationRecord

    belongs_to :status_list, class_name: "StatusList"
    belongs_to :creator, class_name: "User"
    belongs_to :assignee, class_name: "User", optional: true

    validates :title, presence: true
    validates :priority, presence: true, inclusion: {in: %w(low medium high)}

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = Card.all
  end

  def show
  end

  def new
    @card = Card.new
  end

  def new_team_card
    @card = Card.new
    @status_list_id = params[:status_list_id]
  end

  def create
    @card = Card.new(card_params)
    respond_to do |format|
      if @card.save
        format.html {redirect_to @card, notice: 'Tarjeta creada con éxito'}
        format.json {render :show, status: :created, location: @card}
      else
        format.html {render new_team_card_path(status_list_id: @card.status_list_id), status: :unprocessable_entity, locals: { card: @card }}
        format.json {render json: @card.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html {redirect_to @card, notice: 'Tarjeta actualizada con éxito'}
        format.json {render :show, status: :created, location: @card}
      else
        format.html {render :edit, status: :unprocessable_entity, locals: { card: @card }}
        format.json {render json: @card.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path, notice: 'Tarjeta eliminada con éxito'
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:title, :description, :priority, :creator_id, :assignee_id, :status_list_id)
  end

end

app/views/cards/_form.html.erb

<%= form_with(model: @card, local: true) do |form| %>
  <% if @card.errors.any? %>
    <div style="color: red;">
      <h4><%= pluralize(@card.errors.count, 'error') %> prohibited this card from being saved:</h4>
      <ul>
        <% @card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, "Título", class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control rounded-pill' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descripción", class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control rounded' %>
  </div>

  <div class="mb-3">
    <%= form.label :priority, "Prioridad", class: 'form-label' %>
    <%= form.select :priority, ['low', 'medium', 'high'], { prompt: 'Seleccione Prioridad' }, class: 'form-select rounded-pill' %>
  </div>

  <%= form.hidden_field :creator_id, value: current_user.id %>

  <div class="mb-3">
    <%= form.label :assignee_id, "Asignado", class: 'form-label' %>
    <%= form.collection_select :assignee_id, User.all, :id, :full_name, { prompt: 'Seleccione Asignado' }, class: 'form-select rounded-pill' %>
  </div>

  <div class="mb-3">
    <%= form.label :status_list_id, "Estado", class: 'form-label' %>
    <%= form.collection_select :status_list_id, StatusList.all, :id, :title, { prompt: 'Seleccione Lista de Estado' }, class: 'form-select rounded-pill' %>
  </div>

  <div class="d-flex justify-content-between">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
    <%= link_to 'Volver', cards_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/cards/_tform.html.erb

<%= form_with(model: @card, local: true) do |form| %>
  <% if @card.errors.any? %>
    <div style="color: red;">
      <h4><%= pluralize(@card.errors.count, 'error') %> prohibited this card from being saved:</h4>
      <ul>
        <% @card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% users = StatusList.find(@status_list_id).board.team.users %>

  <div class="mb-3">
    <%= form.label :title, "Título", class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control rounded-pill' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descripción", class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control rounded' %>
  </div>

  <div class="mb-3">
    <%= form.label :priority, "Prioridad", class: 'form-label' %>
    <%= form.select :priority, ['low', 'medium', 'high'], { prompt: 'Seleccione Prioridad' }, class: 'form-select rounded-pill' %>
  </div>

  <%= form.hidden_field :creator_id, value: current_user.id %>

  <div class="mb-3">
    <%= form.label :assignee_id, "Asignado", class: 'form-label' %>
    <%= form.collection_select :assignee_id, users, :id, :username, { prompt: 'Seleccione Asignado' }, class: 'form-select rounded-pill' %>
  </div>

  <%= form.hidden_field :status_list_id, value: @status_list_id %>
  <br>
  <div class="d-flex justify-content-between">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
    <%= link_to 'Volver', cards_path, class: 'btn btn-secondary' %>
  </div>
  
<% end %>

app/views/cards/_uform.html.erb

<%= form_with(model: @card, local: true) do |form| %>
  <% if @card.errors.any? %>
    <div style="color: red;">
      <h4><%= pluralize(@card.errors.count, 'error') %> prohibited this card from being saved:</h4>
      <ul>
        <% @card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, "Título", class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control rounded-pill' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descripción", class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control rounded' %>
  </div>

  <div class="mb-3">
    <%= form.label :priority, "Prioridad", class: 'form-label' %>
    <%= form.select :priority, ['low', 'medium', 'high'], { prompt: 'Seleccione Prioridad' }, class: 'form-select rounded-pill' %>
  </div>

  <div class="mb-3">
    <%= form.label :assignee_id, "Asignado", class: 'form-label' %>
    <%= form.collection_select :assignee_id, User.all, :id, :full_name, { prompt: 'Seleccione Asignado' }, class: 'form-select rounded-pill' %>
  </div>

  <div class="mb-3">
    <%= form.label :status_list_id, "Estado", class: 'form-label' %>
    <%= form.collection_select :status_list_id, StatusList.all, :id, :title, { prompt: 'Seleccione Lista de Estado' }, class: 'form-select rounded-pill' %>
  </div>
  <br>
  <div class="d-flex justify-content-between">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
    <%= link_to 'Volver', cards_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-8">
            <div class="card-body">
                <h1 class="my-4">Editar tarea</h1>
                <%= render 'uform' %>
            </div>
        </div>
    </div>
</div>

app/views/cards/index.html.erb
<div class="card">
  <h1 class="my-4">Lista de tareas</h1>

  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Título</th>
          <th scope="col">Estado</th>
          <th scope="col">Tabla</th>
          <th scope="col">Equipo</th>
        </tr>
      </thead>
      <tbody>
        <% @cards.each do |card| %>
          <% if card.status_list.board.team.users.include?(current_user) %>
            <tr>
              <td> <%= link_to card.title, card_path(card), class: 'text-decoration-none' %> </td>
              <td>
                <% status_list = StatusList.find(card.status_list_id) %>
                <%= link_to (StatusList.find(card.status_list_id)).title, status_list_path(status_list), class: 'text-decoration-none' %>
              </td>
              <td>
                <% board = Board.find((StatusList.find(card.status_list_id)).board_id) %>
                <%= link_to (Board.find((StatusList.find(card.status_list_id)).board_id)).title, board_path(board), class: 'text-decoration-none' %>
              </td>
              <td>
                <% team = Team.find((Board.find((StatusList.find(card.status_list_id)).board_id)).team_id) %>
                <%= link_to (Team.find((Board.find((StatusList.find(card.status_list_id)).board_id)).team_id)).name, team_path(team), class: 'text-decoration-none' %>
              </td>
            </tr>
          <% else %>
            <tr>
              <td> <%= card.title %> </td>
              <td> <%= StatusList.find(card.status_list_id).title %> </td>
              <td> <%= Board.find(StatusList.find(card.status_list_id).board_id).title %> </td>
              <td> <%= Team.find(Board.find(StatusList.find(card.status_list_id).board_id).team_id).name %> </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/cards/new.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-8">
            <div class="card-body">
                <h1 class="my-4">Crear tarea</h1>
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/cards/new_team_card.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-8">
            <div class="card-body">
                <h1 class="my-4">Crear tarea</h1>
                <%= render 'tform' %>
            </div>
        </div>
    </div>
</div>

app/views/cards/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title"><%= @card.title %></h1>
          <p class="card-text">
            <strong>Descripción:</strong>
            <%= @card.description %>
          </p>
          <p class="card-text">
            <strong>Prioridad:</strong>
            <%= @card.priority %>
          </p>
          <p class="card-text">
            <strong>Creador:</strong>
            <%= @card.creator.full_name %>
          </p>
          <p class="card-text">
            <strong>Asignado a:</strong>
            <%= @card.assignee.full_name if @card.assignee %>
          </p>
          <br>
          <div>
            <div class="d-flex">
              <% if @card.status_list.board.team.users.include?(current_user) %>
                <%= link_to 'Editar', edit_card_path(@card), class: 'btn btn-sm btn-warning me-2' %>
                <%= button_to 'Eliminar', card_path(@card), method: :delete, data: { turbo_confirm: '¿Estás segura/o de eliminar esta tarea?' }, class: 'btn btn-sm btn-danger me-2' %>
              <% end %>
              <%= link_to 'Volver', cards_path, class: 'btn btn-sm btn-secondary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>