config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  resources :boards

  resources :status_lists

  resources :cards
  get 'new_team_card', to: 'cards#new_team_card', as: :new_team_card

  resources :teams

  resources :users

  resources :tu_linkers

  resources :all_boards

  # get 'all_boards', to: 'all_boards#index', as: :all_boards
  # get 'login', to: 'sessions#new'  
  # post 'login', to: 'sessions#create' 
  # get 'signup', to: 'users#new', as: :signup  
  # post 'signup', to: 'users#create' 
  # get "up" => "rails/health#show", as: :rails_health_check 
  # get 'boards', to: 'boards#show', as: :user_
  # get 'boards/index', to: 'boards#index', as: :tables
  # get '/boards/:id', to: 'boards#show', as: :board
  # delete 'logout', to: 'sessions#destroy', as: :logout
  # resources :users, only: [:new, :create]
 
end

app/models/status_list.rb
class StatusList < ApplicationRecord

    belongs_to :board, class_name: "Board"
    has_many :cards, dependent: :destroy

    validates :title, presence: true

end

app/controllers/status_lists_controller.rb
class StatusListsController < ApplicationController
  before_action :set_status_list, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @status_list = StatusList.new
    @board_id = params[:board_id]
  end

  def create
    @status_list = StatusList.new(status_list_params)
    respond_to do |format|
      if @status_list.save
        format.html {redirect_to board_path(@status_list.board_id), notice: 'Lista de estado creada exitosamente.'}
        format.json {render :show, status: :created, location: @status_list}
      else
        format.html {render :new, status: :unprocessable_entity, locals: {board_id: params[:board_id]}}
        format.json {render json: @status_list.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @status_list.update(status_list_params)
        format.html {redirect_to board_path(@status_list.board_id), notice: 'Lista de estado actualizada exitosamente.'}
        format.json {render :show, status: :created, location: @status_list}
      else
        format.html {render :edit, status: :unprocessable_entity, locals: {board_id: params[:board_id]}}
        format.json {render json: @status_list.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @status_list.destroy
    respond_to do |format|
      format.html {redirect_to board_path(@status_list.board_id), notice: 'Lista de estado eliminada exitosamente.'}
      format.json {head :no_content}
    end
  end

  private

  def set_status_list
    @status_list = StatusList.find(params[:id])
  end

  def status_list_params
    params.require(:status_list).permit(:title, :board_id)
  end

end

app/helpers/status_lists_helper.rb
module StatusListsHelper
end

app/views/status_lists/_form.html.erb
<%= form_with model: status_list, local: true do |form| %>
    <% if @status_list.errors.any? %>
        <div style="color: red;">
            <h4><%= pluralize(@status_list.errors.count, "error") %> prohibited this status from being saved:</h4>
            <ul>
                <% @status_list.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <br><br>
    <div class="form-group mb-3 col-md-12">
        <%= form.label :title, "Título" %>
        <%= form.text_field :title, class: 'form-control rounded-pill' %>
    </div>

    <%= form.hidden_field :board_id, value: @board_id %>
    <br>
    <div class="d-flex justify-content-between">
        <%= form.submit "Crear", class: "btn btn-primary" %>
        <%= link_to "Volver", board_path(@board_id), class: "btn btn-secondary" %>
    </div>
<% end %>

app/views/status_lists/_uform.html.erb
<%= form_with model: status_list, local: true do |form| %>
    <% if @status_list.errors.any? %>
        <div style="color: red;">
            <h4><%= pluralize(@status_list.errors.count, "error") %> prohibited this status from being saved:</h4>
            <ul>
                <% @status_list.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <br><br>
    <div class="form-group mb-3 col-md-11">
        <%= form.label :title, "Título" %>
        <%= form.text_field :title, class: 'form-control rounded-pill' %>
    </div>
    <%= form.submit "Crear", class: "btn btn-primary" %>
<% end %>

app/views/status_lists/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-6">
            <div class="card-body">
                <h1>Renombrar estado</h1>
                <%= render 'uform', status_list: @status_list, board_id: @board_id %>
            </div>
        </div>
    </div>
</div>

app/views/status_lists/new.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="card col-md-6">
            <div class="card-body">
                <h1>Nuevo estado</h1>
                <%= render 'form', status_list: @status_list, board_id: @board_id %>
            </div>
        </div>
    </div>
</div>

app/views/status_lists/show.html.erb
<div class="card">
    <div class="card-body">
        <h1 class="my-4"><%= @status_list.title %></h1>
        <% status_list = @status_list %>
        <div class="d-flex">
            <%= link_to 'Renombrar', edit_status_list_path(@status_list), class: 'btn btn-info mb-4 me-2' %>
            <%= link_to 'Nueva tarea', new_team_card_path(status_list_id: status_list.id) , class: 'btn btn-primary mb-4 me-2' %>
            <%= button_to 'Eliminar', status_list_path(@status_list), method: :delete, data: { turbo_confirm: '¿Estás segura/o de eliminar esta tabla?' }, class: 'btn btn-danger mb-4' %>
        </div>
        <br>
        <% if @status_list.cards.any? %>
            <ul class="list-group">
                <% @status_list.cards.each do |card| %>
                    <li class="list-group-item">
                        <div>
                            <h4><strong><%= link_to card.title, card_path(card), class: 'text-decoration-none' %></strong></h4>
                        </div>
                        <div>
                            <strong>Description:</strong> <%= card.description %>
                        </div>
                        <div>
                            <strong>Priority:</strong> <%= card.priority %>
                        </div>
                        <div>
                            <strong>Creator:</strong> <%= card.creator.username %>
                        </div>
                        <div>
                            <strong>Assignee:</strong> <%= card.assignee.username if card.assignee %>
                        </div>
                    </li>
                <% end %>
            </ul>
        <% else %>
            <p class="mt-3">No hay tarjetas en esta lista.</p>
        <% end %>
    </div> 
</div>